freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  name: build
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH =~ 'release/.*' || $CIRRUS_PR != ''
  # increase timeout since we use a single task for building cache and testing
  timeout_in: 90m
  env:
    BUILD_MODE: normal
    GPG_VERSION: stable
    LOCAL_BUILDS: /home/rnpuser/local-builds
    LOCAL_INSTALLS: /home/rnpuser/local-installs
  user_setup_script: |
    pkg install -y sudo
    # add rnpuser
    pw useradd -n rnpuser -m
    echo 'rnpuser ALL=(ALL) NOPASSWD: ALL' > /usr/local/etc/sudoers.d/rnpuser
    # change ownership for the cloned repo
    chown -R rnpuser:rnpuser "$PWD"
  before_install_script: |
    . ci/env.inc.sh
    su rnpuser -c ci/before_install.sh
  dependencies_cache:
    folder: $LOCAL_INSTALLS
    fingerprint_script: sha256 ci/install.sh && git ls-remote https://github.com/riboseinc/ruby-rnp.git HEAD
  install_script: |
    # cirrus cache doesn't seem to retain ownership
    mkdir -p "$LOCAL_INSTALLS"
    chown -R rnpuser:rnpuser "$LOCAL_INSTALLS"
    # install
    . ci/env.inc.sh
    su rnpuser -c ci/install.sh
  script: |
    . ci/env.inc.sh
    su rnpuser -c ci/main.sh

