= RNP

== Introduction

"rnp" is a set of OpenPGP (RFC4880) tools that works on Linux, *BSD and
macOS as a replacement of GnuPG. It is maintained by Ribose after being
forked from NetPGP, itself originally written for NetBSD.

"librnp" is the library used by rnp for all OpenPGP functions, useful
for developers to build against. Thanks to Alistair, it is a "real"
library, not a wrapper like GPGME of GnuPG.

NetPGP was originally written (and still maintained) by Alistair Crooks
of NetBSD.

== Status

image:https://travis-ci.org/rnpgp/rnp.svg?branch=master["Travis CI Build Status", link="https://travis-ci.org/rnpgp/rnp"]
image:https://img.shields.io/coverity/scan/12616.svg["Coverity Scan Build Status", link="https://scan.coverity.com/projects/rnpgp-rnp"]
image:https://codecov.io/gh/rnpgp/rnp/branch/master/graph/badge.svg["Code coverage", link="https://codecov.io/gh/rnpgp/rnp"]

== Supported Platforms

Currently supported platforms:

* Fedora 25
* RHEL/CentOS 7

Upcoming supported platforms:

* Ubuntu 14.04 LTS, 16.04 LTS, 17.04
* Debian 8, 9
* OpenSUSE Leap 42.2, 42.3
* SLES 12

== link:docs/installation.adoc[Installation]

== link:docs/cli-usage.adoc[Using CLI tool]

== link:docs/c-usage.adoc[Using RNP’s C API in your projects]

== Versioning

RNP follows the http://semver.org/[semantic versioning] syntax.

=== Checking versions

The output of `rnp --version` contains the `git` hash of
the version the binary was built from, which value is generated when
`cmake` runs. Consequently, a release tarball generated with `make
dist` will contain this hash version.

=== Historic

The first version of rnp started at `0.8.0` to indicate its development
completeness (or lack thereof).
