/*
 * Copyright (c) 2018, [Ribose Inc](https://www.ribose.com).
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1.  Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 * 2.  Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include <rnp/rnp_types.h>
#include "pgp-key.h"
#include "crypto.h"
#include <string.h>

int
encrypt_highlevel()
{
    rnp_t        rnp = {};
    rnp_params_t params = {};
    rnp_ctx_t    ctx = {};
    pgp_key_t *  key = NULL;
    int          result = 1;
    const char * message = "RNP encryption sample message";
    char         encrypted_message[10000] = {0};
    FILE *       efile = NULL;
    size_t       encrypted_len = 0;

    /* setup rnp parameters */
    rnp_params_init(&params);
    params.pubpath = strdup("pubring.pgp");
    params.secpath = strdup("secring.pgp");
    params.ks_pub_format = RNP_KEYSTORE_GPG;
    params.ks_sec_format = RNP_KEYSTORE_GPG;
    params.password_provider = {.callback = rnp_password_provider_string,
                                .userdata = (void *) "password"};

    /* initialize rnp structure */
    if (rnp_init(&rnp, &params) != RNP_SUCCESS) {
        fprintf(stdout, "failed to init rnp");
        goto finish;
    }

    /* load keys - you should have keys, generated by the generate example */
    if (!rnp_key_store_load_keys(&rnp, true)) {
        fprintf(stdout, "failed to load keyrings: run ./generate example first\n");
        goto finish;
    }

    /* initalize context with some data from rnp_t */
    if (rnp_ctx_init(&ctx, &rnp) != RNP_SUCCESS) {
        fprintf(stdout, "failed to initialize context\n");
        goto finish;
    }

    /* do we need armored output? */
    ctx.armor = true;
    /* encrypted file name and modification date */
    ctx.filename = strdup("source.txt");
    ctx.filemtime = time(NULL);
    /* compression algorithm and level (1-9), PGP_C_NONE to not use compression */
    ctx.zalg = PGP_C_ZIP;
    ctx.zlevel = 6;
    /* symmetric encryption algorithm */
    ctx.ealg = PGP_SA_AES_256;
    /* hash, used for key derivation if password-based encryption is used */
    ctx.halg = PGP_HASH_SHA256;
    /* whether use new AEAD encryption or old CFB */
    ctx.aalg = PGP_AEAD_NONE;

    /* encrypt to the password as well as to the key. See the rnp_encrypt_add_password() source
       for the details. This call uses rnp->password_provider as password source, i.e. this
       call will add 'password' */
    if (rnp_encrypt_add_password(&ctx) != RNP_SUCCESS) {
        fprintf(stdout, "Failed to add password\n");
        goto finish;
    }
    /* find and add recipient public key. Key may be searched by userid, keyid, fingerprint or
     * grip */
    key = rnp_key_store_get_key_by_name(rnp.pubring, "rsa@key", NULL);
    if (!key) {
        fprintf(stdout, "key rsa@key not found, did you run generate example?\n");
        goto finish;
    }
    if (!list_append(&ctx.recipients, &key, sizeof(key))) {
        fprintf(stdout, "failed to add key to recipient list\n");
        goto finish;
    }

    /* within this call you should pass large enough output buffer, otherwise encryption will
     * run twice */
    if (rnp_protect_mem(&ctx,
                        message,
                        strlen(message),
                        encrypted_message,
                        sizeof(encrypted_message),
                        &encrypted_len) != RNP_SUCCESS) {
        fprintf(stdout, "encryption failed\n");
        goto finish;
    }

    fprintf(stdout, "%.*s", (int) encrypted_len, encrypted_message);

    if (!(efile = fopen("encrypted.asc", "w+"))) {
        fprintf(stdout, "failed to write encrypted data to file\n");
        goto finish;
    }
    fwrite(encrypted_message, 1, encrypted_len, efile);
    fclose(efile);

    result = 0;
finish:
    rnp_ctx_free(&ctx);
    rnp_params_free(&params);
    rnp_end(&rnp);
    return result;
}

int
main(int argc, char **argv)
{
    return encrypt_highlevel();
}