#! /bin/sh

version=$(awk '/^#define[ \t]+RNP_VERIFY_H_/ { print $3 }' verify.h)
name=rnpv-${version}

(cd .. &&
	mv files ${name} &&
	tar --exclude CVS -cvzf $HOME/${name}.tar.gz ${name} &&
	ls -al $HOME/${name}.tar.gz &&
	mv ${name} files)

