name: centos8-openssl

on:
  push:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/centos8-ossl.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  CORES: 2
  CODECOV_TOKEN: dbecf176-ea3f-4832-b743-295fd71d0fad
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  LC_LANG: C.UTF-8
  USE_STATIC_DEPENDENCIES: yes
  DOWNLOAD_RUBYRNP: Off
  CRYPTO_BACKEND: openssl

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: tgagor/centos:stream8
    timeout-minutes: 70
    strategy:
      fail-fast: false
      matrix:
        env:
          - BUILD_MODE: normal
            CC: gcc
            CXX: g++
          - BUILD_MODE: normal
            CC: clang
            CXX: clang++
          - BUILD_MODE: sanitize
            CC: clang
            CXX: clang++
    env: ${{ matrix.env }}
    name: centos:stream8 OpenSSL [test mode ${{ matrix.env.BUILD_MODE }}; CC ${{ matrix.env.CC }}]
    steps:
      - run: |
          yum -y install git
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Add rnpuser
        run: |
          useradd rnpuser
          yum -y -q install sudo
          echo -e "rnpuser\tALL=(ALL)\tNOPASSWD:\tALL" > /etc/sudoers.d/rnpuser
          echo -e "rnpuser\tsoft\tnproc\tunlimited\n" > /etc/security/limits.d/30-rnpuser.conf
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
          exec su rnpuser -c ci/install_noncacheable_dependencies.sh
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ github.workflow }}-${{ runner.os }}-${{ matrix.env.BUILD_MODE }}-${{ matrix.env.CC }}-${{ hashFiles('ci/**') }}-${{ hashFiles('.github/workflows/**') }}
      - name: Build cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          chown -R rnpuser:rnpuser $PWD
          exec su rnpuser -c ci/install_cacheable_dependencies.sh
      - name: Install OpenSSL-devel
        run: |
          yum -y install openssl-devel
      - name: tests
        run: |
          set -x
          chown -R rnpuser:rnpuser $PWD
          exec su rnpuser -c ci/run.sh
      - name: supported-features
        run: |
          set -euxo pipefail
          export LD_LIBRARY_PATH="${JSONC_INSTALL}/lib64:${RNP_INSTALL}/lib64"
          $RNP_INSTALL/bin/rnp --version > rnp-version
          # Make sure that we support all features which should be supported
          supported=( RSA ELGAMAL DSA ECDH ECDSA EDDSA \
            IDEA TRIPLEDES CAST5 BLOWFISH AES128 AES192 AES256 CAMELLIA128 CAMELLIA192 CAMELLIA256 \
            MD5 SHA1 RIPEMD160 SHA256 SHA384 SHA512 SHA224 SHA3-256 SHA3-512 \
            ZIP ZLIB BZip2 \
            "NIST P-256" "NIST P-384" "NIST P-521" Ed25519 Curve25519 secp256k1 )
          unsupported=( TWOFISH EAX OCB )
          sm2=( SM2 SM4 SM3 "SM2 P-256" )
          bp=( brainpoolP256r1 brainpoolP384r1 brainpoolP512r1 )
          # SM2
          unsupported+=("${sm2[@]}")
          unsupported+=("${bp[@]}")
          for feature in "${supported[@]}"
          do
            [ $(grep -ci "$feature" rnp-version) -ge "1" ]
          done
          for feature in "${unsupported[@]}"
          do
            [ $(grep -ci "$feature" rnp-version) == "0" ]
          done
