name: fedora36

on:
  push:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/fedora36.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

env:
  CORES: 2
  CODECOV_TOKEN: dbecf176-ea3f-4832-b743-295fd71d0fad
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  LC_LANG: C.UTF-8
  USE_STATIC_DEPENDENCIES: yes
  DOWNLOAD_RUBYRNP: Off

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: fedora:36
    timeout-minutes: 70
    strategy:
      fail-fast: false
      matrix:
        env:
          - BUILD_MODE: normal
            CC: gcc
            CXX: g++
          - BUILD_MODE: sanitize
            CC: clang
            CXX: clang++
    env: ${{ matrix.env }}
    name: fedora36 Botan [mode ${{ matrix.env.BUILD_MODE }}; CC ${{ matrix.env.CC }}; GnuPG ${{ matrix.env.GPG_VERSION }}; SM2 ${{ matrix.env.ENABLE_SM2 }}]
    steps:
      - run: |
          yum -y install git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Add rnpuser
        run: |
          useradd rnpuser
          yum -y -q install sudo
          echo -e "rnpuser\tALL=(ALL)\tNOPASSWD:\tALL" > /etc/sudoers.d/rnpuser
          echo -e "rnpuser\tsoft\tnproc\tunlimited\n" > /etc/security/limits.d/30-rnpuser.conf
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
          exec su rnpuser -c ci/install_noncacheable_dependencies.sh
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ github.workflow }}-${{ runner.os }}-${{ matrix.env.BUILD_MODE }}-${{ matrix.env.CC }}-gpg-${{ matrix.env.GPG_VERSION }}-sm2-${{ matrix.env.ENABLE_SM2 }}-${{ hashFiles('ci/**') }}-${{ hashFiles('.github/workflows/**') }}
      - name: Build cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          chown -R rnpuser:rnpuser $PWD
          exec su rnpuser -c ci/install_cacheable_dependencies.sh
      - name: tests
        run: |
          set -x
          chown -R rnpuser:rnpuser $PWD
          exec su rnpuser -c ci/run.sh
      - name: symbol-visibility
        run: |
          set -euxo pipefail
          nm --defined-only -g $RNP_INSTALL/lib64/librnp*.so > exports
          [ $(grep -c dst_close exports) == "0" ]
          [ $(grep -c Botan exports) == "0" ]
          [ $(grep -c rnp_version_string_full exports) == "1" ]
  pkgconfig-cmake-target:
    runs-on: ubuntu-latest
    # TODO: re-enable when the following can pass
    if: "${{ false && !contains(github.event.head_commit.message, 'skip ci') }}"
    container:
      image: fedora:36
    timeout-minutes: 10
    strategy:
      matrix:
        env:
          - BUILD_SHARED_LIBS: yes
          - BUILD_SHARED_LIBS: no
    env: ${{ matrix.env }}
    continue-on-error: true
    steps:
      - run: |
          yum -y install git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test
        run: |

          # cmake
          set -euxo pipefail
          export USE_STATIC_DEPENDENCIES=no
          ci/install_noncacheable_dependencies.sh
          ci/install_cacheable_dependencies.sh

          . ci/env.inc.sh

          # build+install
          build_and_install /usr

          # check for install issues
          check_build
          build_example_pkgconfig
      - name: Package
        run: |
          set -euxo pipefail
          yum install -y rpm-build
          cpack -G RPM
