name: fuzzing

on:
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - 'Brewfile'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - 'version.txt'

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
    # HACK: temporarily use our oss-fuzz fork (rnp-botan-3.6) which updates the
    # rnp build to Botan 3.6.0. Revert to google/oss-fuzz@master once
    # google/oss-fuzz#15882 is merged.
    - name: Build Fuzzers
      id: build
      uses: ronaldtse/oss-fuzz/infra/cifuzz/actions/build_fuzzers@rnp-botan-3.6
      with:
        oss-fuzz-project-name: 'rnp'
        dry-run: false
    - name: Run Fuzzers
      uses: ronaldtse/oss-fuzz/infra/cifuzz/actions/run_fuzzers@rnp-botan-3.6
      with:
        oss-fuzz-project-name: 'rnp'
        fuzz-seconds: 300
        dry-run: false
    - name: Upload Crash
      uses: actions/upload-artifact@v4
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
